name: Java CI
on: push
jobs:
  job-1:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        run: actions/upload-artifact@v2
  job-2:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: job-1
    steps:
      - name: Test
        run: ci/unit-test-app.sh
  job-3:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: job-1
    steps:
    - name: Build
      run: ci/build-app.sh
