name: Java CI
on: push
jobs:
  job-1:
    name: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone step
        run: git clone https://github.com/mnau23/github-actions-katas.git
  job-2:
    name: Test
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: job-1
    steps:
      - name: Test step
        run: ci/unit-test-app.sh
  job-3:
    name: Build
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: job-1
    steps:
      - name: Build step
        run: ci/build-app.sh
