name: Java CI
on: push
jobs:
  my-job:
    job-1:
      name: Clone-down
      runs-on: ubuntu-latest
      container: gradle:6-jdk11
      uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
    job-2:
      name: Test
      runs-on: ubuntu-latest
      container: gradle:6-jdk11
      needs: job-1
      run: ci/unit-test-app.sh
    job-3:
      name: Build
      runs-on: ubuntu-latest
      container: gradle:6-jdk11
      needs: job-1
      run: ci/build-app.sh
